# use the official ubuntu image
image: ubuntu

variables:
  GIT_SUBMODULE_STRATEGY: normal

debug-build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential clang cmake git vim-common zlib1g-dev
  script: 
    - mkdir -p debug
    - cd debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: 1 week
    paths:
      - debug/quabs
  cache:
    paths:
      - debug/

release-build:
  stage: build
  before_script:
    - apt-get update -qq && apt-get install -y -qq build-essential clang cmake git vim-common zlib1g-dev
  script: 
    - mkdir -p release
    - cd release
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    expire_in: 1 week
    paths:
      - release/quabs
  cache:
    paths:
      - release/

# run tests using the binary built before
test-debug:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3
  script:
    - ./test/run.py debug/quabs --execution --unittests --fuzztests
  dependencies:
    - debug-build

test-release:
  stage: test
  before_script:
    - apt-get update -qq && apt-get install -y -qq python3
  script:
    - ./test/run.py release/quabs --execution --unittests --fuzztests
  dependencies:
    - release-build
